remote: master

remotes:
    master:
        backend: girder_hashsum
        url: https://drake-girder.csail.mit.edu
        folder_path: /collection/drake/files
        # Do NOT upload directly to "master". For now, switch to "devel".
        disable_upload: true

    devel:
        backend: girder_hashsum
        url: https://drake-girder.csail.mit.edu
        folder_path: /collection/drake-devel/files
        overlay: master
