# Blech.
sh_binary(
    name = "external_data_download",
    srcs = ["external_data.sh"],
    data = [
        "girder_conf.sh",
        "girder.gitconfig",
    ],
    visibility=["//visibility:public"],
)
