# Blech.
sh_binary(
    name = "download_data_script",
    srcs = ["download_data.sh"],
    data = [
        "girder_conf.sh",
        "girder.gitconfig",
    ],
    visibility=["//visibility:public"],
)
