#!/bin/bash
set -e -u

# Proxy to use Bazel binary, but access to PWD.

workspace_dir=$(cd $(dirname $0)/.. && pwd)
bin_dir=${workspace_dir}/bazel-bin/external/external_data_bazel_pkg
bin=${bin_dir}/cli

do_build=
if [[ $# -gt 0 && $1 == --do_build ]]; then
    do_build=1
    shift
fi

if [[ ! -f ${bin} || -n $do_build ]]; then
    # TODO(eric.cousineau): Is there a way to use the previous build config,
    # so that Bazel doesn't switch the symlink and possibly lose whatever
    # other artifacts the user may want???
    bazel build @external_data_bazel_pkg//:cli
fi

${bin} "$@"
